services:
  postgres:
    image: postgres:latest
    #    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  api:
    build: .
    #    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: