spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?useSSL=false&serverTimezone=UTC
    username: kpasd002
    password: test1234
  jpa:
    hibernate:
      ddl-auto: create
#logging:
#  level:
#    root: debug