#spring.application.name=springboot-clean-arch-boilterplate
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
spring:
  application:
    name: springboot-clean-arch-boilterplate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari.connection-timeout: 20000
    hikari.maximum-pool-size: 10
    hikari.minimum-idle: 5
    hikari.idle-timeout: 300000
    hikari.max-lifetime: 1200000
  profiles:
    active: development