spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres?useSSL=false&serverTimezone=UTC
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
#logging:
#  level:
#    root: debug